//Fetch TOKEN
export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

//Fetch UserData
export const fetch_MAKE_USER_DATA_LOADING = "fetch_MAKE_USER_DATA_LOADING";
export const fetch_MAKE_USER_DATA_SUCCESS = "fetch_MAKE_USER_DATA_SUCCESS";
export const fetch_MAKE_USER_DATA_ERROR = "fetch_MAKE_USER_DATA_ERROR";